name: cs224r-env
channels:
  - conda-forge  
  - nvidia     
  - pytorch           
dependencies:
  - python=3.10
  - pytorch=2.6.0             
  - pytorch-cuda=12.4
  - numpy>=1.26
  - scikit-learn>=1.5
  - pandas>=2.2
  - pip                     
  - pip:
      - transformers==4.41.0  
      - datasets==2.20.0
      - accelerate>=0.27.0
      - evaluate==0.4.3
      - bitsandbytes==0.45.5
      - peft==0.10.0
      - wandb==0.17.2
      - tensorboard==2.16.2
      - tqdm>=4.66.3
      - openai==1.23.1
      - torch_tb_profiler==0.4.1
