name: cs224r-env
channels:
  - pytorch
  - nvidia
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.1
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - numpy=1.24.3
  - pip:
    - transformers==4.35.0
    - datasets==2.14.5
    - accelerate==0.23.0
    - wandb==0.16.0
    - tqdm==4.66.1
    - pandas==2.1.0
    - scikit-learn==1.3.1
    - openai==1.3.0  # For the Nemotron reward model evaluation
    - tensorboard==2.14.0  # Alternative to wandb for experiment tracking
    - bitsandbytes==0.41.0  # For optional 8-bit quantization of models
    - peft==0.5.0  # In case you want to use parameter-efficient fine-tuning
    - evaluate==0.4.0
    - torch_tb_profiler==0.4.1  # For profiling performance 